//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APCRTC__Web_service.ServiceReference1 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPassengerDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPassengerDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPassengerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPassengerDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostPassengerDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void PostPassengerDetails(string n, string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PostPassengerDetails", ReplyAction="*")]
        System.Threading.Tasks.Task PostPassengerDetailsAsync(string n, string origin, string destination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : APCRTC__Web_service.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<APCRTC__Web_service.ServiceReference1.WebService1Soap>, APCRTC__Web_service.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPassengerDetails() {
            return base.Channel.GetPassengerDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPassengerDetailsAsync() {
            return base.Channel.GetPassengerDetailsAsync();
        }
        
        public void PostPassengerDetails(string n, string origin, string destination) {
            base.Channel.PostPassengerDetails(n, origin, destination);
        }
        
        public System.Threading.Tasks.Task PostPassengerDetailsAsync(string n, string origin, string destination) {
            return base.Channel.PostPassengerDetailsAsync(n, origin, destination);
        }
    }
}
